graph TD;
	__start__([<p>__start__</p>]):::first
	retrieval_node(retrieval_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieval_node;
	retrieval_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

    classDef default fill:#D4EDDA, stroke:#4CAF50, color:#155724;
    classDef first fill:#CCE5FF, stroke:#007BFF, color:#004085;
    classDef last fill:#F8D7DA, stroke:#DC3545, color:#721C24;